Repository APS-4ID-POLAR/ipython-polar, pull requests merged in 2020-11, with the labels that each got.

#35 Set default timeout on EpicsSignalBase
  profile_bluesky/startup/instrument/framework/initialize.py
Labels: maintenance

#38 Temperature controller
  profile_bluesky/startup/instrument/devices/lakeshore336.py
  profile_bluesky/startup/instrument/devices/lakeshore340.py
  profile_bluesky/startup/instrument/devices/lakeshores.py
Labels: bug

#44 Various devices
  profile_bluesky/startup/instrument/devices/__init__.py
  profile_bluesky/startup/instrument/devices/apd.py
  profile_bluesky/startup/instrument/devices/cyberstar.py
  profile_bluesky/startup/instrument/devices/flat_mirror.py
  profile_bluesky/startup/instrument/devices/monochromator.py
  profile_bluesky/startup/instrument/devices/ruby_motors.py
  profile_bluesky/startup/instrument/devices/scaler.py
  profile_bluesky/startup/instrument/devices/srs810.py
  profile_bluesky/startup/instrument/devices/srs_amplifiers.py
  profile_bluesky/startup/instrument/devices/toroidal_mirror.py
Labels: enhancement
