Repository APS-4ID-POLAR/ipython-polar, pull requests merged in 2021-01, with the labels that each got.

#54 Mono stuck
  profile_bluesky/startup/instrument/plans/energy_plans.py
Labels: bug

#53 update user_calc for compatibility with qxscan.
  profile_bluesky/startup/instrument/devices/user_calc.py
Labels: bug

#61 update for 2021_1 conda environment
  profile_bluesky/startup/instrument/framework/initialize.py
  profile_bluesky/startup/instrument/framework/metadata.py
Labels: maintenance

#63 Code cleanup
  .github/workflows/flake8_lint.yml
  profile_bluesky/startup/instrument/__init__.py
  profile_bluesky/startup/instrument/callbacks/abs_plot.py
  profile_bluesky/startup/instrument/callbacks/ideas/__init__.py
  profile_bluesky/startup/instrument/callbacks/ideas/lesson1.py
  profile_bluesky/startup/instrument/devices/apd.py
  profile_bluesky/startup/instrument/devices/aps_source.py
  profile_bluesky/startup/instrument/devices/cyberstar.py
  profile_bluesky/startup/instrument/devices/filters.py
  profile_bluesky/startup/instrument/devices/flat_mirror.py
  profile_bluesky/startup/instrument/devices/ge_controller.py
  profile_bluesky/startup/instrument/devices/huber.py
  profile_bluesky/startup/instrument/devices/kbic.py
  profile_bluesky/startup/instrument/devices/lakeshore336.py
  profile_bluesky/startup/instrument/devices/lakeshore340.py
  profile_bluesky/startup/instrument/devices/lakeshores.py
  profile_bluesky/startup/instrument/devices/magnets.py
  profile_bluesky/startup/instrument/devices/monochromator.py
  profile_bluesky/startup/instrument/devices/phaseplates.py
  profile_bluesky/startup/instrument/devices/qxscan_setup.py
  profile_bluesky/startup/instrument/devices/ruby_motors.py
  profile_bluesky/startup/instrument/devices/scaler.py
  profile_bluesky/startup/instrument/devices/slits.py
  profile_bluesky/startup/instrument/devices/spec_config.py
  profile_bluesky/startup/instrument/devices/srs810.py
  profile_bluesky/startup/instrument/devices/srs_amplifiers.py
  profile_bluesky/startup/instrument/devices/toroidal_mirror.py
  profile_bluesky/startup/instrument/devices/uptable.py
  profile_bluesky/startup/instrument/devices/user_calc.py
  profile_bluesky/startup/instrument/devices/xbpm.py
  profile_bluesky/startup/instrument/framework/__init__.py
  profile_bluesky/startup/instrument/framework/callbacks.py
  profile_bluesky/startup/instrument/framework/check_bluesky.py
  profile_bluesky/startup/instrument/framework/check_python.py
  profile_bluesky/startup/instrument/framework/initialize.py
  profile_bluesky/startup/instrument/framework/metadata.py
  profile_bluesky/startup/instrument/framework/user_dir.py
  profile_bluesky/startup/instrument/mpl/__init__.py
  profile_bluesky/startup/instrument/mpl/console.py
  profile_bluesky/startup/instrument/mpl/notebook.py
  profile_bluesky/startup/instrument/plans/energy_plans.py
  profile_bluesky/startup/instrument/plans/slits_plans.py
  profile_bluesky/startup/instrument/session_logs.py
  profile_bluesky/startup/instrument/utils/done_signal.py
  profile_bluesky/startup/instrument/utils/example_load_setup.py
  profile_bluesky/startup/instrument/utils/test.py
  profile_bluesky/startup/instrument/utils/tracking_signal.py
Labels: enhancement

#49 Phase retarders
  profile_bluesky/startup/instrument/devices/__init__.py
  profile_bluesky/startup/instrument/devices/apd.py
  profile_bluesky/startup/instrument/devices/aps_source.py
  profile_bluesky/startup/instrument/devices/magnets.py
  profile_bluesky/startup/instrument/devices/monochromator.py
  profile_bluesky/startup/instrument/devices/phaseplates.py
  profile_bluesky/startup/instrument/devices/scaler.py
  profile_bluesky/startup/instrument/devices/wavefunction_generator.py
  profile_bluesky/startup/instrument/plans/__init__.py
  profile_bluesky/startup/instrument/plans/energy_plans.py
  profile_bluesky/startup/instrument/plans/local_preprocessors.py
  profile_bluesky/startup/instrument/plans/local_scans.py
  profile_bluesky/startup/instrument/utils/__init__.py
  profile_bluesky/startup/instrument/utils/local_rd.py
Labels: enhancement

#69 Fix db subscription to RE.
  profile_bluesky/startup/instrument/framework/initialize.py
Labels: bug
